[phases.setup]
nixPkgs = ["python39", "google-chrome", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt", "pip install gunicorn"]

[start]
cmd = "gunicorn -w 1 -b 0.0.0.0:${PORT:-8080} --timeout 600 --preload app:app"
