services:
  - type: web
    name: copart-scraper
    env: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 300 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
